apiVersion: v1
kind: ServiceAccount
metadata:
   name: viewer
   namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kube-system
  name: viewerrole
rules:
  - apiGroups: ['']
    resources:
    - pods
    verbs:
    - get
    - list
    - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: viewerbinding
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: viewer
    namespace: default
roleRef:
  kind: Role
  name: viewerrole
  apiGroup: rbac.authorization.k8s.io
